USE [hyj_formation]
GO

/****** Object:  Table [dbo].[EventStore]    Script Date: 10/14/2022 4:15:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EventStore](
	[StreamId] [int] NOT NULL,
	[Date] [date] NOT NULL,
	[Event] [ntext] NOT NULL,
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SequenceNumber] [int] NOT NULL,
 CONSTRAINT [PK_EventStore] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


